package graphic;

import controller.PathagonController;
import javax.swing.JOptionPane;

public class graphicMenuGame extends javax.swing.JFrame {

    /**
     * Creates new form menuBoard
     */
    public graphicMenuGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        level = new javax.swing.JComboBox();
        playGame = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dificultad: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, 20));

        name.setText("Player1");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 240, 30));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 20));

        level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fácil", "Medio", "Difícil" }));
        getContentPane().add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 240, -1));

        playGame.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        playGame.setText("Jugar");
        playGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playGameMouseClicked(evt);
            }
        });
        getContentPane().add(playGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphic/image/Menu.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playGameMouseClicked
        int dif=0;
        if(level.getSelectedIndex()==0){
            dif=1;
        }else{
            if(level.getSelectedIndex()==1){
               dif=3; 
            }else{
                dif=4;
            }
        }
        String player ="";
        if(name.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"No ingreso nombre del Jugador: 'Player1' es su nombre","Mensaje de Advertencia",JOptionPane.ERROR_MESSAGE);
            player="Player1";           
        }else{
            player=name.getText(); 
        }
        PathagonController c=new PathagonController(player,dif);        
        graphicBoardGame view = new graphicBoardGame(c);
        view.player.setText(player);
        c.setView(view);
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_playGameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(graphicMenuGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(graphicMenuGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(graphicMenuGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(graphicMenuGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new graphicMenuGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox level;
    private javax.swing.JTextField name;
    private javax.swing.JButton playGame;
    // End of variables declaration//GEN-END:variables
}
